"""
Use Gazebo Python services to set and get parameters

Inspect parameters using services

gz service -i -s /world/servo/list_parameters

Service providers [Address, Request Message Type, Response Message Type]:
  tcp://127.0.0.1:53842, gz.msgs.Empty, gz.msgs.ParameterDeclarations


gz service --service /world/servo/list_parameters --reqtype gz.msgs.Empty --reptype gz.msgs.ParameterDeclarations --req ""

parameter_declarations {
  name: "JointPositionController.servo.servo_arm_joint.cmd_offset"
  type: "gz_msgs.Double"
}
parameter_declarations {
  name: "JointPositionController.servo.servo_arm_joint.cmd_min"
  type: "gz_msgs.Double"
}
parameter_declarations {
  name: "JointPositionController.servo.servo_arm_joint.cmd_max"
  type: "gz_msgs.Double"
}
parameter_declarations {
  name: "JointPositionController.servo.servo_arm_joint.i_max"
  type: "gz_msgs.Double"
}
parameter_declarations {
  name: "JointPositionController.servo.servo_arm_joint.i_gain"
  type: "gz_msgs.Double"
}
parameter_declarations {
  name: "JointPositionController.servo.servo_arm_joint.i_min"
  type: "gz_msgs.Double"
}
parameter_declarations {
  name: "JointPositionController.servo.servo_arm_joint.d_gain"
  type: "gz_msgs.Double"
}
parameter_declarations {
  name: "JointPositionController.servo.servo_arm_joint.p_gain"
  type: "gz_msgs.Double"
}

"""

import os

from argparse import ArgumentParser

from google.protobuf import symbol_database
from google.protobuf.any_pb2 import Any

# World and model defaults
DEFAULT_WORLD = "servo"
DEFAULT_MODEL = "servo"
DEFAULT_JOINT = "servo_arm_joint"
DEFAULT_CONTROLLER = "JointPositionController"
DEFAULT_TIMEOUT_MS = 1000

# Supported Gazebo versions
GZ_VERSION_GARDEN = "garden"
GZ_VERSION_HARMONIC = "harmonic"
GZ_VERSION_IONIC = "ionic"


def gz_version():
    """Return the environment variable GZ_VERSION if set, else default to 'harmonic'"""
    return os.environ.get("GZ_VERSION", GZ_VERSION_HARMONIC)


if gz_version() == GZ_VERSION_GARDEN:
    from gz.msgs9.double_pb2 import Double
    from gz.msgs9.parameter_pb2 import Parameter
    from gz.msgs9.parameter_error_pb2 import ParameterError
    from gz.msgs9.parameter_name_pb2 import ParameterName
    from gz.msgs9.parameter_value_pb2 import ParameterValue
elif gz_version() == GZ_VERSION_HARMONIC:
    from gz.msgs10.double_pb2 import Double
    from gz.msgs10.parameter_pb2 import Parameter
    from gz.msgs10.parameter_error_pb2 import ParameterError
    from gz.msgs10.parameter_name_pb2 import ParameterName
    from gz.msgs10.parameter_value_pb2 import ParameterValue
elif gz_version() == GZ_VERSION_IONIC:
    from gz.msgs11.double_pb2 import Double
    from gz.msgs11.parameter_pb2 import Parameter
    from gz.msgs11.parameter_error_pb2 import ParameterError
    from gz.msgs11.parameter_name_pb2 import ParameterName
    from gz.msgs11.parameter_value_pb2 import ParameterValue


# Importing gz.transport into the module global scope causes an odd
# multiprocessing conflict with dronecan. This is a workaround.
def gz_node():
    if gz_version() == GZ_VERSION_GARDEN:
        from gz.transport12 import Node
    elif gz_version() == GZ_VERSION_HARMONIC:
        from gz.transport13 import Node
    elif gz_version() == GZ_VERSION_IONIC:
        from gz.transport14 import Node

    return Node()


class InvalidParameterError(Exception):
    pass


# unpack_any generated by Claude 3.5 Sonnet
# "Unpack a google.protobuf.any_pb2.Any using the type_url"
def unpack_any(any_msg):
    """Unpack a google.protobuf.Any message using its type_url.

    Args:
        any_msg: google.protobuf.Any message to unpack

    Returns:
        Unpacked protobuf message
    """
    # Extract the message type name from type_url
    # type_url format: "type.googleapis.com/package.MessageType"
    type_name = any_msg.type_url.split("/")[-1]

    # Get the global symbol database
    db = symbol_database.Default()

    try:
        # Look up the message class by its full name
        message_class = db.GetSymbol(type_name)
        # Create a new message instance
        message = message_class()
        # Unpack the Any message into it
        any_msg.Unpack(message)
        return message
    except KeyError:
        raise ValueError(f"Unknown message type: {type_name}")


def is_any_empty(any_msg):
    """Check if Any message is empty or null.

    Args:
        any_msg: google.protobuf.Any message to check

    Returns:
        bool: True if empty/null, False otherwise
    """
    # NOTE: do not check 'not any_msg.value' as this provides a false
    #       positive in the event the value has the default value.
    return any_msg is None or not any_msg.type_url


def get_param(registry, name, timeout_ms):
    """Get a parameter from a registry"""
    node = gz_node()
    service_name = f"{registry}/get_parameter"
    request = ParameterName()
    request.name = name
    response = ParameterValue()

    result, response = node.request(
        service_name, request, ParameterName, ParameterValue, timeout_ms
    )

    # Validate
    if not result:
        raise InvalidParameterError(
            f"Failed to get parameter [{name}] service call failed"
        )

    if is_any_empty(response.data):
        raise InvalidParameterError(f"Failed to get parameter [{name}] not declared")

    return unpack_any(response.data)


def set_param(registry, name, value, timeout_ms):
    """Set a (double) parameter from a registry"""
    node = gz_node()
    service_name = f"{registry}/set_parameter"
    double_msg = Double()
    double_msg.data = value
    request = Parameter()
    request.name = name
    request.value.Pack(double_msg)
    response = ParameterError()

    result, response = node.request(
        service_name, request, Parameter, ParameterError, timeout_ms
    )

    # Validate
    if not result:
        raise InvalidParameterError(
            f"Failed to set parameter [{name}] service call failed"
        )

    if response.data != ParameterError.SUCCESS:
        raise InvalidParameterError(f"Failed to set parameter [{name}] {response}")


def main():
    """Example demonstrating how to set and get dynamic parameters"""

    # Command line args
    parser = ArgumentParser(description="Get controller PIDs")
    parser.add_argument("--world", default=DEFAULT_WORLD, type=str, help="world name")
    parser.add_argument("--model", default=DEFAULT_MODEL, type=str, help="model name")
    parser.add_argument("--joint", default=DEFAULT_JOINT, type=str, help="joint name")
    parser.add_argument(
        "--controller",
        default=DEFAULT_CONTROLLER,
        type=str,
        help="joint controller system",
    )
    parser.add_argument(
        "--timeout_ms", default=DEFAULT_TIMEOUT_MS, type=str, help="timeout (ms)"
    )
    args = parser.parse_args()

    timeout_ms = args.timeout_ms

    world_name = args.world
    model_name = args.model
    joint_name = args.joint
    system_name = args.controller

    registry = f"/world/{world_name}"
    prefix = f"{system_name}.{model_name}.{joint_name}."
    names = [
        "p_gain",
        "i_gain",
        "d_gain",
        "i_max",
        "i_min",
        "cmd_max",
        "cmd_min",
        "cmd_offset",
    ]

    # get params
    print(f"Get PID params")
    print(f"system_name: {system_name}")
    print(f"model_name: {model_name}")
    print(f"joint_name: {joint_name}")
    for i, name in enumerate(names):
        scopedName = prefix + name
        try:
            value = get_param(registry, scopedName, timeout_ms)
            print(f"{name}: {value.data}")

        except InvalidParameterError as ex:
            print(ex)


if __name__ == "__main__":
    main()
